a =int (input("Enter a number: " ))
b =int(input("Enter another number: "))
print("Sum :", a + b)
print("Difference :", a - b)
print("Product :", a * b)
print("Division:", a / b)
print("Exponentation :", a ** b)